language: android
android:
  components:
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-21.1.1
    - android-21
  licenses:
    - '.+'