language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - '.+'